# yadr defaults
tap "homebrew/bundle"
brew "ctags"
brew "ghi"
brew "git"
brew "hub"
brew "macvim"
brew "reattach-to-user-namespace"
brew "the_silver_searcher"
brew "tmux"
brew "zsh"

# personal
brew "poetry"
brew "pyenv"

tap "homebrew/cask"

cask "rectangle"
cask "spotify"

cask "iterm2"
cask "visual-studio-code"
cask "tableplus"
cask "docker"
cask "alfred"
cask "notion"
cask "figma"
cask "google-drive"
